# .readthedocs.yaml

version: 2

# 设置构建环境
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

# 指定 Sphinx 配置文件路径
sphinx:
  configuration: source/conf.py  # 请确保 conf.py 文件路径正确

# 指定要安装的依赖项（如果有其他工具需求，如 Node.js，请加入相应配置）
python:
  install:
    - requirements: requirements.txt

# 可选，生成其他文档格式，例如 PDF 或 EPUB，如果不需要可以不配置
# formats:
#   - pdf
#   - epub
