version: 2

build:
  os: linux
  tools:
    python: "3.8"
  jobs:
    install:
      - method: python
        path: .
        command:
          - python -m pip install --upgrade pip setuptools
          - python -m pip install --upgrade sphinx
          - python -m pip install --exists-action=w --no-cache-dir -r requirements.txt
    build:
      - sphinx-build -T -b html -d _build/doctrees -D language=en . _build/html

formats:
  - html
